### ISSUE TITLE
Please move the 'l' keybinding away from emacs.js

### ISSUE THREAD

**Issue by wh5a** [decklin/yakshave#1]
It conflicts with Google Reader's "like" shortcut, and doesn't fits with Emacs anyway.

**Comment by decklin** [comment]
Those couple of keys are from info-mode. I've been meaning to create a separate file for them; I'll go ahead and do that.

**Comment by decklin** [comment]
fixed in 1.11

**Comment by decklin** [comment]
Er, 1.1. Anyway, I forgot to mention that you could override with something like

'l': {onkeydown: function() {return false;}}

I think I'll add the return-false part as yak.functions.punt or something to save typing.
