### ISSUE TITLE
Install doesn't seem to work

### ISSUE THREAD

**Issue by bpostow** [decklin/yakshave#10]
I installed it, it shows up in my list of extetnsions, but it doesn't seem to actually DO anything... Since no one else seems to have this problem, I'm assuming I did something dumb...

I'm running Chrome 6.4 and Windows XP

**Comment by decklin** [comment]
What did you enable on the options page? Try anything in the "additional bindings" box right on the page there? e.g. paste this in...

```
yak.bindings.add({'M-q': {
    onkeydown: function(e) { alert('Hello, world!'); }
  }
});
```

**Comment by bpostow** [comment]
that doesn't seem to do anything either...

I have standard, unix and emacs checked... as well as  Use the key labeled "Alt" as Meta

I'm not using yakserver, I shouldn't need to be, right?

**Comment by decklin** [comment]
Correct, yakserver is not required. I'm really not sure what's happening to you. I'll see if I can find a Windows machine to reproduce (don't have one here).

**Comment by bpostow** [comment]
Ok, So, I added the binding listed above, and THAT seems to work, but even though I have emacs and unix checked, C-b doesn't do anything...do I need to load the bindings from an URL?

**Comment by bpostow** [comment]
Ok, so evidently, it DID install, but I don' seem to have set it up correctly. I'll move that to a separate comment...
