### ISSUE TITLE
Emacs Ctrl-v shortcut breaks on Google Sites

### ISSUE THREAD

**Issue by wh5a** [decklin/yakshave#4]
Try to edit something on sites.google.com. Ctrl-v doesn't paste, instead it scrolls down the page. It seems that Google Sites isn't using a standard textarea element, and you're having trouble detecting it.

**Comment by decklin** [comment]
There are two ways to approach this: allow more specificity in what elements to include/exclude, or add inclusion/exclusion by site. Off the top of my head, I need to exclude anything with contentEditable turned on... which is already more complicated than simply checking element types. Maybe a CSS-style selector?

In the meantime, I'll go sign up for Google Sites and see what their non-textarea textarea is made out of.

**Comment by decklin** [comment]
It turns out they're just using contentEditable. In the future maybe there could be conditional bindings for that case but for now I'm just disabling everything if that's turned on (I get all the GTK+ keys anyway). Fix is in 3efbc39.

**Comment by wh5a** [comment]
How do I set the GTK+ keybindings? I followed http://kb.mozillazine.org/Emacs_Keybindings_(Firefox) but nothing happened.

**Comment by decklin** [comment]
Which method are you using? I'm using the .gtkrc-2.0 one, which has worked for as long as I can remember. Does /usr/share/themes/Emacs/gtk-2.0-key exist?

**Comment by wh5a** [comment]
I'm not running gnome. Probably that's why.

**Comment by decklin** [comment]
I'm not either... I think you have to use the gconf method if you are.
