### ISSUE TITLE
seems not work for me

### ISSUE THREAD

**Issue by stattrak-dragonlore** [decklin/yakshave#7]
ubuntu 9.04
chrome 4.0.302.2 dev
I 've installed this extension. 
But pressing C-b  still show the bookmarks bar.

**Comment by decklin** [comment]
Just C-b, or everything?

**Comment by stattrak-dragonlore** [comment]
I was wrong. The input focus was on.text element..So it's a feature， right?

**Comment by decklin** [comment]
Yes. If you want C-b to do the right thing in text fields (across the system, not just in chrome), set your GTK+ key theme to "Emacs".
